import type { Config } from "tailwindcss";
const { fontFamily } = require("tailwindcss/defaultTheme");

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        transparent: "transparent",
        black: "#000000",
        white: "#FFFFFF",
        darkblue: "#122187",
        secondary: "#F6F7F9",
        "neutral-100-alpha": "rgba(0, 0, 0, 0.08)",
        "neutral-200-alpha": "rgba(0, 0, 0, 0.16)",
        "neutral-300-alpha": "rgba(0, 0, 0, 0.22)",
        "primary-100-alpha": "rgba(51, 72, 255, 0.08)",
        "primary-200-alpha": "rgba(51, 72, 255, 0.16)",
        "primary-300-alpha": "rgba(51, 72, 255, 0.22)",
        neutral: {
          0: "#FFFFFF",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          100: "#F0F7FF",
          200: "#E0EDFF",
          300: "#CCE0FF",
          400: "#5261FE",
          500: "#3348FF",
          600: "#162DF3",
          700: "#1C2EB0",
        },
        warning: {
          100: "#FFF6D1",
          200: "#FFED9E",
          300: "#FFDE66",
          400: "#F58700",
          500: "#DB6E00",
          600: "#C76300",
          700: "#81340E",
        },
        success: {
          100: "#DBFFE1",
          200: "#BEFEC7",
          300: "#93F2A2",
          400: "#00BD1F",
          500: "#00A81C",
          600: "#009419",
          700: "#0C6E1F",
        },
        danger: {
          100: "#FFF0F1",
          200: "#FFDEE0",
          300: "#FFB4BF",
          400: "#F31246",
          500: "#DF0C3D",
          600: "#CB0B38",
          700: "#930B2F",
        },
        feature: {
          100: "#F6EBFF",
          200: "#F0DBFF",
          300: "#EACCFF",
          400: "#AC3DF5",
          500: "#9F1FF4",
          600: "#910BE9",
          700: "#6D12A1",
        },
        info: {
          100: "#D4FCF3",
          200: "#B3F8EB",
          300: "#89EADB",
          400: "#00B8B8",
          500: "#00ABAB",
          600: "#009E9E",
          700: "#09726B",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      textColor: ({ colors }) => ({
        "color-base": "#14181F",
        secondary: colors.neutral[700],
        muted: "#6F7C8E",
        active: "#3348FF",
        warning: "#DB6E00",
        success: "#00A81C",
        danger: "#DF0C3D",
        feature: "#9F1FF4",
        info: "#00ABAB",
        invert: colors.white,
      }),
      backgroundColor: ({ colors }) => ({
        base: colors.white,
        secondary: "#F6F7F9",
        overlay: colors.white,
        lower: "#F6F7F9",
      }),
      borderColor: ({ colors }) => ({
        base: colors.neutral[200],
        secondary: colors.neutral[300],
        muted: colors.neutral[400],
        active: "#3348FF",
        warning: "#DB6E00",
        success: "#00A81C",
        danger: "#DF0C3D",
        feature: "#9F1FF4",
        info: "#00ABAB",
        invert: colors.white,
        intense: colors.neutral[400],
      }),
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
};
export default config;
